plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - spec/dummy/**/*
    - lib/generators/**/*
    - bin/**
    - config/**/*
    - vendor/**/*
    - Rakefile

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/**/*