plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - spec/dummy/**/*
    - lib/generators/**/*
    - bin/**
    - config/**/*
    - vendor/**/*
    - Rakefile

Layout/LineLength:
  Max: 150

# DISABLED

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*